# https://gist.github.com/naumanbadar/aad6a25974b30adcb3c89b5f868627da
version: "3.3"

# make sure that docker machine has enough memory to run the cluster.
# setting it up to 4GB seems to work.

services:

  backend:
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - cassandra-load-keyspace
    env_file:
      - ./backend/.env
    ports:
    - "8000:8000"
    restart: always

  cassandra-seed:
    image: cassandra:latest
#    ports:
#      - "9042:9042"
    volumes:
      - ./init_keyspace.cql:/schema.cql
      - "cassandra_data_seed:/var/lib/cassandra"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
#      needed for setting up custom cluster name
      - "CASSANDRA_DC=se1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
#    restart: always
    container_name: node-seed
    # command: /bin/bash -c "sleep 60 && cqlsh -f /schema.cql"

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:latest
    depends_on:
      - cassandra-seed
    volumes:
      - ./init_keyspace.cql:/schema.cql
    command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra-seed -f /schema.cql"

  cassandra-1:
    image: cassandra:latest
    volumes:
      - "cassandra_data_1:/var/lib/cassandra"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
#      needed for setting up custom cluster name
      - "CASSANDRA_DC=se1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    depends_on:
      - cassandra-seed
#    restart: always
    container_name: cassandra-1

  cassandra-2:
    image: cassandra:latest
    volumes:
      - "cassandra_data_2:/var/lib/cassandra"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
#      needed for setting up custom cluster name
      - "CASSANDRA_DC=se1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    depends_on:
      - cassandra-seed
#    restart: always
    container_name: cassandra-2

volumes:
  cassandra_data_seed:
  cassandra_data_1:
  cassandra_data_2: